[package]
name = "arx-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "arx"
path = "src/main.rs"

[dependencies]
arx-formats = { path = "../arx-formats" }
glam.workspace = true
arx-physics = { path = "../arx-physics" }
arx-script = { path = "../arx-script" }
anyhow.workspace = true
clap.workspace = true
